### ISSUE TITLE
Blueprint Joker inconsistencies

### ISSUE THREAD

**Issue by gobbi9** [MikaSchoenmakers/MikasBalatro#2]
I have not tested against all Jokers in this mod, but against Grudgeful Joker Blueprint does copy the ability but then the Grudgeful Joker itself does not trigger.

Against other Jokers like Suit Alley it seems to work, but the badge "incompatible" is still shown on the Blueprint Joker.

I have not tested it with Brainstorm but I suppose these issues might also happen, since it is another Joker that copies abilities.

**Comment by MikaSchoenmakers** [comment]
Unfortunately, the Blueprint Joker currently has a bug within Steamodded (The modloader that my mod depends on), so it will always show incompatible even when it really is compatible. The Grudgeful Joker not working is a bug with my mod though and I'll fix it in an upcoming update, thank you for reporting!

**Comment by MikaSchoenmakers** [comment]
The Grudgeful Joker bug is fixed in the latest update. It is no longer compatible with blueprint. The visual bug will hopefully get fixed with a steamodded update, so I'm closing this issue.
