### ISSUE TITLE
Buying Batman Joker crashes the game

### ISSUE THREAD

**Issue by gobbi9** [MikaSchoenmakers/MikasBalatro#3]
![image](https://github.com/MikaSchoenmakers/MikasBalatro/assets/5932540/1ac81378-e1cf-4d13-9f49-12a3aa6de8ec)

<img width="619" alt="batman" src="https://github.com/MikaSchoenmakers/MikasBalatro/assets/5932540/cdf03774-2d80-4814-bbf4-a2267d7cfce0">

Probably a conflict with one of the following mods I have installed:

<img width="538" alt="mods" src="https://github.com/MikaSchoenmakers/MikasBalatro/assets/5932540/d2e03fe8-efe4-412f-b49f-eb9c77fa6b01">

**Comment by gobbi9** [comment]
Similar error as in https://github.com/notmario/MoreFluff/issues/1#issuecomment-2016809940

**Comment by MikaSchoenmakers** [comment]
JellyMod causes a lot of incompatibilities, as seen in both [their readme](https://github.com/jamesthejellyfish/JellyMod/tree/main?tab=readme-ov-file#compatibility-warning) and [my readme](https://github.com/MikaSchoenmakers/MikasBalatro?tab=readme-ov-file#mod-incompatibility). You could try the partial fix that is described in mine, which might potentially solve it, but if not it's just a problem with JellyMod unfortunately.

**Comment by gobbi9** [comment]
Thanks, I disabled the JellyMod for now.
